# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: usuarios.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eusuarios.proto\x12\x08usuarios\"\x07\n\x05\x45mpty\")\n\x08UserList\x12\x1d\n\x05users\x18\x01 \x03(\x0b\x32\x0e.usuarios.User\"/\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x63urso\x18\x03 \x01(\t28\n\x05Users\x12/\n\x08GetUsers\x12\x0f.usuarios.Empty\x1a\x12.usuarios.UserListB\x17\xaa\x02\x14ProyectoRedes.Protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'usuarios_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\024ProyectoRedes.Protos'
  _globals['_EMPTY']._serialized_start=28
  _globals['_EMPTY']._serialized_end=35
  _globals['_USERLIST']._serialized_start=37
  _globals['_USERLIST']._serialized_end=78
  _globals['_USER']._serialized_start=80
  _globals['_USER']._serialized_end=127
  _globals['_USERS']._serialized_start=129
  _globals['_USERS']._serialized_end=185
# @@protoc_insertion_point(module_scope)
